/**
 * This class is generated by jOOQ
 */
package org.jooq.ateamcomp354.projectmanagerapp.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row;
import org.jooq.Row3;
import org.jooq.ateamcomp354.projectmanagerapp.tables.ActivitylinksTable;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivitylinksRecord extends UpdatableRecordImpl<ActivitylinksRecord> implements Record3<Integer, Integer, Integer> {

	private static final long serialVersionUID = 371129981;

	/**
	 * Setter for <code>activityLinks.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>activityLinks.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>activityLinks.from_activity_id</code>.
	 */
	public void setFromActivityId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>activityLinks.from_activity_id</code>.
	 */
	public Integer getFromActivityId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>activityLinks.to_activity_id</code>.
	 */
	public void setToActivityId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>activityLinks.to_activity_id</code>.
	 */
	public Integer getToActivityId() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return ActivitylinksTable.ACTIVITYLINKS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return ActivitylinksTable.ACTIVITYLINKS.FROM_ACTIVITY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return ActivitylinksTable.ACTIVITYLINKS.TO_ACTIVITY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getFromActivityId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getToActivityId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActivitylinksRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActivitylinksRecord value2(Integer value) {
		setFromActivityId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActivitylinksRecord value3(Integer value) {
		setToActivityId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActivitylinksRecord values(Integer value1, Integer value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ActivitylinksRecord
	 */
	public ActivitylinksRecord() {
		super(ActivitylinksTable.ACTIVITYLINKS);
	}

	/**
	 * Create a detached, initialised ActivitylinksRecord
	 */
	public ActivitylinksRecord(Integer id, Integer fromActivityId, Integer toActivityId) {
		super(ActivitylinksTable.ACTIVITYLINKS);

		setValue(0, id);
		setValue(1, fromActivityId);
		setValue(2, toActivityId);
	}
}
