/**
 * This class is generated by jOOQ
 */
package org.jooq.ateamcomp354.projectmanagerapp.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row;
import org.jooq.Row2;
import org.jooq.ateamcomp354.projectmanagerapp.tables.ActivitylinksTable;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivitylinksRecord extends TableRecordImpl<ActivitylinksRecord> implements Record2<Integer, Integer> {

	private static final long serialVersionUID = 439893315;

	/**
	 * Setter for <code>activityLinks.from_activity_id</code>.
	 */
	public void setFromActivityId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>activityLinks.from_activity_id</code>.
	 */
	public Integer getFromActivityId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>activityLinks.to_activity_id</code>.
	 */
	public void setToActivityId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>activityLinks.to_activity_id</code>.
	 */
	public Integer getToActivityId() {
		return (Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return ActivitylinksTable.ACTIVITYLINKS.FROM_ACTIVITY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return ActivitylinksTable.ACTIVITYLINKS.TO_ACTIVITY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getFromActivityId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getToActivityId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActivitylinksRecord value1(Integer value) {
		setFromActivityId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActivitylinksRecord value2(Integer value) {
		setToActivityId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActivitylinksRecord values(Integer value1, Integer value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ActivitylinksRecord
	 */
	public ActivitylinksRecord() {
		super(ActivitylinksTable.ACTIVITYLINKS);
	}

	/**
	 * Create a detached, initialised ActivitylinksRecord
	 */
	public ActivitylinksRecord(Integer fromActivityId, Integer toActivityId) {
		super(ActivitylinksTable.ACTIVITYLINKS);

		setValue(0, fromActivityId);
		setValue(1, toActivityId);
	}
}
