/**
 * This class is generated by jOOQ
 */
package org.jooq.ateamcomp354.projectmanagerapp.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row;
import org.jooq.Row2;
import org.jooq.ateamcomp354.projectmanagerapp.tables.Memberlist;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemberlistRecord extends TableRecordImpl<MemberlistRecord> implements Record2<Integer, Integer> {

	private static final long serialVersionUID = 326750478;

	/**
	 * Setter for <code>memberList.member_list_id</code>.
	 */
	public void setMemberListId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>memberList.member_list_id</code>.
	 */
	public Integer getMemberListId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>memberList.user_id</code>.
	 */
	public void setUserId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>memberList.user_id</code>.
	 */
	public Integer getUserId() {
		return (Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Memberlist.MEMBERLIST.MEMBER_LIST_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Memberlist.MEMBERLIST.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getMemberListId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberlistRecord value1(Integer value) {
		setMemberListId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberlistRecord value2(Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberlistRecord values(Integer value1, Integer value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MemberlistRecord
	 */
	public MemberlistRecord() {
		super(Memberlist.MEMBERLIST);
	}

	/**
	 * Create a detached, initialised MemberlistRecord
	 */
	public MemberlistRecord(Integer memberListId, Integer userId) {
		super(Memberlist.MEMBERLIST);

		setValue(0, memberListId);
		setValue(1, userId);
	}
}
