/**
 * This class is generated by jOOQ
 */
package org.jooq.ateamcomp354.projectmanagerapp.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row;
import org.jooq.Row3;
import org.jooq.ateamcomp354.projectmanagerapp.tables.Projectactivities;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectactivitiesRecord extends TableRecordImpl<ProjectactivitiesRecord> implements Record3<Integer, Integer, Integer> {

	private static final long serialVersionUID = 1232246248;

	/**
	 * Setter for <code>projectActivities.project_activities_id</code>.
	 */
	public void setProjectActivitiesId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>projectActivities.project_activities_id</code>.
	 */
	public Integer getProjectActivitiesId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>projectActivities.project_id</code>.
	 */
	public void setProjectId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>projectActivities.project_id</code>.
	 */
	public Integer getProjectId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>projectActivities.activity_id</code>.
	 */
	public void setActivityId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>projectActivities.activity_id</code>.
	 */
	public Integer getActivityId() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Projectactivities.PROJECTACTIVITIES.PROJECT_ACTIVITIES_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Projectactivities.PROJECTACTIVITIES.PROJECT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Projectactivities.PROJECTACTIVITIES.ACTIVITY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getProjectActivitiesId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getProjectId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getActivityId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProjectactivitiesRecord value1(Integer value) {
		setProjectActivitiesId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProjectactivitiesRecord value2(Integer value) {
		setProjectId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProjectactivitiesRecord value3(Integer value) {
		setActivityId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProjectactivitiesRecord values(Integer value1, Integer value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ProjectactivitiesRecord
	 */
	public ProjectactivitiesRecord() {
		super(Projectactivities.PROJECTACTIVITIES);
	}

	/**
	 * Create a detached, initialised ProjectactivitiesRecord
	 */
	public ProjectactivitiesRecord(Integer projectActivitiesId, Integer projectId, Integer activityId) {
		super(Projectactivities.PROJECTACTIVITIES);

		setValue(0, projectActivitiesId);
		setValue(1, projectId);
		setValue(2, activityId);
	}
}
