/**
 * This class is generated by jOOQ
 */
package org.jooq.ateamcomp354.projectmanagerapp.tables;


import ateamcomp354.projectmanagerapp.jooq.converters.StatusConverter;
import ateamcomp354.projectmanagerapp.model.Status;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.ateamcomp354.projectmanagerapp.DefaultSchema;
import org.jooq.ateamcomp354.projectmanagerapp.Keys;
import org.jooq.ateamcomp354.projectmanagerapp.tables.records.ActivityRecord;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivityTable extends TableImpl<ActivityRecord> {

	private static final long serialVersionUID = -1862402807;

	/**
	 * The reference instance of <code>activity</code>
	 */
	public static final ActivityTable ACTIVITY = new ActivityTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ActivityRecord> getRecordType() {
		return ActivityRecord.class;
	}

	/**
	 * The column <code>activity.id</code>.
	 */
	public final TableField<ActivityRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>activity.project_id</code>.
	 */
	public final TableField<ActivityRecord, Integer> PROJECT_ID = createField("project_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>activity.status</code>.
	 */
	public final TableField<ActivityRecord, Status> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this, "", new StatusConverter());

	/**
	 * The column <code>activity.earliest_start</code>.
	 */
	public final TableField<ActivityRecord, Integer> EARLIEST_START = createField("earliest_start", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>activity.earliest_finish</code>.
	 */
	public final TableField<ActivityRecord, Integer> EARLIEST_FINISH = createField("earliest_finish", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>activity.label</code>.
	 */
	public final TableField<ActivityRecord, String> LABEL = createField("label", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>activity.latest_start</code>.
	 */
	public final TableField<ActivityRecord, Integer> LATEST_START = createField("latest_start", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>activity.latest_finish</code>.
	 */
	public final TableField<ActivityRecord, Integer> LATEST_FINISH = createField("latest_finish", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>activity.duration</code>.
	 */
	public final TableField<ActivityRecord, Integer> DURATION = createField("duration", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>activity.max_duration</code>.
	 */
	public final TableField<ActivityRecord, Integer> MAX_DURATION = createField("max_duration", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>activity.float</code>.
	 */
	public final TableField<ActivityRecord, Integer> FLOAT = createField("float", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>activity.description</code>.
	 */
	public final TableField<ActivityRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>activity.planned_value</code>.
	 */
	public final TableField<ActivityRecord, Integer> PLANNED_VALUE = createField("planned_value", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>activity.actual_cost</code>.
	 */
	public final TableField<ActivityRecord, Integer> ACTUAL_COST = createField("actual_cost", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>activity</code> table reference
	 */
	public ActivityTable() {
		this("activity", null);
	}

	/**
	 * Create an aliased <code>activity</code> table reference
	 */
	public ActivityTable(String alias) {
		this(alias, ACTIVITY);
	}

	private ActivityTable(String alias, Table<ActivityRecord> aliased) {
		this(alias, aliased, null);
	}

	private ActivityTable(String alias, Table<ActivityRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ActivityRecord> getPrimaryKey() {
		return Keys.PK_ACTIVITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ActivityRecord>> getKeys() {
		return Arrays.<UniqueKey<ActivityRecord>>asList(Keys.PK_ACTIVITY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<ActivityRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<ActivityRecord, ?>>asList(Keys.FK_ACTIVITY_PROJECT_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActivityTable as(String alias) {
		return new ActivityTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ActivityTable rename(String name) {
		return new ActivityTable(name, null);
	}
}
