/**
 * This class is generated by jOOQ
 */
package org.jooq.ateamcomp354.projectmanagerapp.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.ateamcomp354.projectmanagerapp.DefaultSchema;
import org.jooq.ateamcomp354.projectmanagerapp.Keys;
import org.jooq.ateamcomp354.projectmanagerapp.tables.records.MemberlistRecord;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Memberlist extends TableImpl<MemberlistRecord> {

	private static final long serialVersionUID = -417480892;

	/**
	 * The reference instance of <code>memberList</code>
	 */
	public static final Memberlist MEMBERLIST = new Memberlist();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<MemberlistRecord> getRecordType() {
		return MemberlistRecord.class;
	}

	/**
	 * The column <code>memberList.member_list_id</code>.
	 */
	public final TableField<MemberlistRecord, Integer> MEMBER_LIST_ID = createField("member_list_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>memberList.user_id</code>.
	 */
	public final TableField<MemberlistRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>memberList</code> table reference
	 */
	public Memberlist() {
		this("memberList", null);
	}

	/**
	 * Create an aliased <code>memberList</code> table reference
	 */
	public Memberlist(String alias) {
		this(alias, MEMBERLIST);
	}

	private Memberlist(String alias, Table<MemberlistRecord> aliased) {
		this(alias, aliased, null);
	}

	private Memberlist(String alias, Table<MemberlistRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<MemberlistRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<MemberlistRecord, ?>>asList(Keys.FK_MEMBERLIST_PROJECT_1, Keys.FK_MEMBERLIST_USERS_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Memberlist as(String alias) {
		return new Memberlist(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Memberlist rename(String name) {
		return new Memberlist(name, null);
	}
}
