/**
 * This class is generated by jOOQ
 */
package org.jooq.ateamcomp354.projectmanagerapp.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.ateamcomp354.projectmanagerapp.DefaultSchema;
import org.jooq.ateamcomp354.projectmanagerapp.Keys;
import org.jooq.ateamcomp354.projectmanagerapp.tables.records.UserprojectsRecord;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Userprojects extends TableImpl<UserprojectsRecord> {

	private static final long serialVersionUID = 18451959;

	/**
	 * The reference instance of <code>userProjects</code>
	 */
	public static final Userprojects USERPROJECTS = new Userprojects();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<UserprojectsRecord> getRecordType() {
		return UserprojectsRecord.class;
	}

	/**
	 * The column <code>userProjects.user_id</code>.
	 */
	public final TableField<UserprojectsRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>userProjects.project_id</code>.
	 */
	public final TableField<UserprojectsRecord, Integer> PROJECT_ID = createField("project_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>userProjects</code> table reference
	 */
	public Userprojects() {
		this("userProjects", null);
	}

	/**
	 * Create an aliased <code>userProjects</code> table reference
	 */
	public Userprojects(String alias) {
		this(alias, USERPROJECTS);
	}

	private Userprojects(String alias, Table<UserprojectsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Userprojects(String alias, Table<UserprojectsRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<UserprojectsRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<UserprojectsRecord, ?>>asList(Keys.FK_USERPROJECTS_USERS_1, Keys.FK_USERPROJECTS_PROJECT_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Userprojects as(String alias) {
		return new Userprojects(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Userprojects rename(String name) {
		return new Userprojects(name, null);
	}
}
