/**
 * This class is generated by jOOQ
 */
package org.jooq.ateamcomp354.projectmanagerapp.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.ateamcomp354.projectmanagerapp.tables.Activity;
import org.jooq.ateamcomp354.projectmanagerapp.tables.records.ActivityRecord;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivityDao extends DAOImpl<ActivityRecord, org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Activity, Integer> {

	/**
	 * Create a new ActivityDao without any configuration
	 */
	public ActivityDao() {
		super(Activity.ACTIVITY, org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Activity.class);
	}

	/**
	 * Create a new ActivityDao with an attached configuration
	 */
	public ActivityDao(Configuration configuration) {
		super(Activity.ACTIVITY, org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Activity.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Activity object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Activity> fetchById(Integer... values) {
		return fetch(Activity.ACTIVITY.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Activity fetchOneById(Integer value) {
		return fetchOne(Activity.ACTIVITY.ID, value);
	}

	/**
	 * Fetch records that have <code>project_id IN (values)</code>
	 */
	public List<org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Activity> fetchByProjectId(Integer... values) {
		return fetch(Activity.ACTIVITY.PROJECT_ID, values);
	}

	/**
	 * Fetch records that have <code>earliest_start IN (values)</code>
	 */
	public List<org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Activity> fetchByEarliestStart(Integer... values) {
		return fetch(Activity.ACTIVITY.EARLIEST_START, values);
	}

	/**
	 * Fetch records that have <code>earliest_finish IN (values)</code>
	 */
	public List<org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Activity> fetchByEarliestFinish(Integer... values) {
		return fetch(Activity.ACTIVITY.EARLIEST_FINISH, values);
	}

	/**
	 * Fetch records that have <code>label IN (values)</code>
	 */
	public List<org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Activity> fetchByLabel(String... values) {
		return fetch(Activity.ACTIVITY.LABEL, values);
	}

	/**
	 * Fetch records that have <code>latest_start IN (values)</code>
	 */
	public List<org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Activity> fetchByLatestStart(Integer... values) {
		return fetch(Activity.ACTIVITY.LATEST_START, values);
	}

	/**
	 * Fetch records that have <code>latest_finish IN (values)</code>
	 */
	public List<org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Activity> fetchByLatestFinish(Integer... values) {
		return fetch(Activity.ACTIVITY.LATEST_FINISH, values);
	}

	/**
	 * Fetch records that have <code>duration IN (values)</code>
	 */
	public List<org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Activity> fetchByDuration(Integer... values) {
		return fetch(Activity.ACTIVITY.DURATION, values);
	}

	/**
	 * Fetch records that have <code>max_duration IN (values)</code>
	 */
	public List<org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Activity> fetchByMaxDuration(Integer... values) {
		return fetch(Activity.ACTIVITY.MAX_DURATION, values);
	}

	/**
	 * Fetch records that have <code>description IN (values)</code>
	 */
	public List<org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Activity> fetchByDescription(String... values) {
		return fetch(Activity.ACTIVITY.DESCRIPTION, values);
	}
}
