/**
 * This class is generated by jOOQ
 */
package org.jooq.ateamcomp354.projectmanagerapp.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.ateamcomp354.projectmanagerapp.tables.ActivitylinksTable;
import org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Activitylinks;
import org.jooq.ateamcomp354.projectmanagerapp.tables.records.ActivitylinksRecord;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivitylinksDao extends DAOImpl<ActivitylinksRecord, Activitylinks, Integer> {

	/**
	 * Create a new ActivitylinksDao without any configuration
	 */
	public ActivitylinksDao() {
		super(ActivitylinksTable.ACTIVITYLINKS, Activitylinks.class);
	}

	/**
	 * Create a new ActivitylinksDao with an attached configuration
	 */
	public ActivitylinksDao(Configuration configuration) {
		super(ActivitylinksTable.ACTIVITYLINKS, Activitylinks.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(Activitylinks object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<Activitylinks> fetchById(Integer... values) {
		return fetch(ActivitylinksTable.ACTIVITYLINKS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public Activitylinks fetchOneById(Integer value) {
		return fetchOne(ActivitylinksTable.ACTIVITYLINKS.ID, value);
	}

	/**
	 * Fetch records that have <code>from_activity_id IN (values)</code>
	 */
	public List<Activitylinks> fetchByFromActivityId(Integer... values) {
		return fetch(ActivitylinksTable.ACTIVITYLINKS.FROM_ACTIVITY_ID, values);
	}

	/**
	 * Fetch records that have <code>to_activity_id IN (values)</code>
	 */
	public List<Activitylinks> fetchByToActivityId(Integer... values) {
		return fetch(ActivitylinksTable.ACTIVITYLINKS.TO_ACTIVITY_ID, values);
	}
}
