/**
 * This class is generated by jOOQ
 */
package org.jooq.ateamcomp354.projectmanagerapp.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.ateamcomp354.projectmanagerapp.tables.Project;
import org.jooq.ateamcomp354.projectmanagerapp.tables.records.ProjectRecord;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectDao extends DAOImpl<ProjectRecord, org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Project, Integer> {

	/**
	 * Create a new ProjectDao without any configuration
	 */
	public ProjectDao() {
		super(Project.PROJECT, org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Project.class);
	}

	/**
	 * Create a new ProjectDao with an attached configuration
	 */
	public ProjectDao(Configuration configuration) {
		super(Project.PROJECT, org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Project.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Project object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Project> fetchById(Integer... values) {
		return fetch(Project.PROJECT.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Project fetchOneById(Integer value) {
		return fetchOne(Project.PROJECT.ID, value);
	}

	/**
	 * Fetch records that have <code>project_name IN (values)</code>
	 */
	public List<org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Project> fetchByProjectName(String... values) {
		return fetch(Project.PROJECT.PROJECT_NAME, values);
	}

	/**
	 * Fetch records that have <code>project_manager_id IN (values)</code>
	 */
	public List<org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Project> fetchByProjectManagerId(Integer... values) {
		return fetch(Project.PROJECT.PROJECT_MANAGER_ID, values);
	}

	/**
	 * Fetch records that have <code>description IN (values)</code>
	 */
	public List<org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Project> fetchByDescription(String... values) {
		return fetch(Project.PROJECT.DESCRIPTION, values);
	}
}
