/**
 * This class is generated by jOOQ
 */
package org.jooq.ateamcomp354.projectmanagerapp.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.ateamcomp354.projectmanagerapp.tables.ProjectmembersTable;
import org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Projectmembers;
import org.jooq.ateamcomp354.projectmanagerapp.tables.records.ProjectmembersRecord;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectmembersDao extends DAOImpl<ProjectmembersRecord, Projectmembers, Integer> {

	/**
	 * Create a new ProjectmembersDao without any configuration
	 */
	public ProjectmembersDao() {
		super(ProjectmembersTable.PROJECTMEMBERS, Projectmembers.class);
	}

	/**
	 * Create a new ProjectmembersDao with an attached configuration
	 */
	public ProjectmembersDao(Configuration configuration) {
		super(ProjectmembersTable.PROJECTMEMBERS, Projectmembers.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(Projectmembers object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<Projectmembers> fetchById(Integer... values) {
		return fetch(ProjectmembersTable.PROJECTMEMBERS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public Projectmembers fetchOneById(Integer value) {
		return fetchOne(ProjectmembersTable.PROJECTMEMBERS.ID, value);
	}

	/**
	 * Fetch records that have <code>project_id IN (values)</code>
	 */
	public List<Projectmembers> fetchByProjectId(Integer... values) {
		return fetch(ProjectmembersTable.PROJECTMEMBERS.PROJECT_ID, values);
	}

	/**
	 * Fetch records that have <code>user_id IN (values)</code>
	 */
	public List<Projectmembers> fetchByUserId(Integer... values) {
		return fetch(ProjectmembersTable.PROJECTMEMBERS.USER_ID, values);
	}
}
