/**
 * This class is generated by jOOQ
 */
package org.jooq.ateamcomp354.projectmanagerapp.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.ateamcomp354.projectmanagerapp.tables.Users;
import org.jooq.ateamcomp354.projectmanagerapp.tables.records.UsersRecord;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersDao extends DAOImpl<UsersRecord, org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Users, Integer> {

	/**
	 * Create a new UsersDao without any configuration
	 */
	public UsersDao() {
		super(Users.USERS, org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Users.class);
	}

	/**
	 * Create a new UsersDao with an attached configuration
	 */
	public UsersDao(Configuration configuration) {
		super(Users.USERS, org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Users.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Users object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Users> fetchById(Integer... values) {
		return fetch(Users.USERS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Users fetchOneById(Integer value) {
		return fetchOne(Users.USERS.ID, value);
	}

	/**
	 * Fetch records that have <code>first_name IN (values)</code>
	 */
	public List<org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Users> fetchByFirstName(String... values) {
		return fetch(Users.USERS.FIRST_NAME, values);
	}

	/**
	 * Fetch records that have <code>last_name IN (values)</code>
	 */
	public List<org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Users> fetchByLastName(String... values) {
		return fetch(Users.USERS.LAST_NAME, values);
	}

	/**
	 * Fetch records that have <code>username IN (values)</code>
	 */
	public List<org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Users> fetchByUsername(String... values) {
		return fetch(Users.USERS.USERNAME, values);
	}
}
