/**
 * This class is generated by jOOQ
 */
package org.jooq.ateamcomp354.projectmanagerapp.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.ateamcomp354.projectmanagerapp.tables.UseractivitiesTable;
import org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Useractivities;
import org.jooq.ateamcomp354.projectmanagerapp.tables.records.UseractivitiesRecord;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UseractivitiesDao extends DAOImpl<UseractivitiesRecord, Useractivities, Integer> {

	/**
	 * Create a new UseractivitiesDao without any configuration
	 */
	public UseractivitiesDao() {
		super(UseractivitiesTable.USERACTIVITIES, Useractivities.class);
	}

	/**
	 * Create a new UseractivitiesDao with an attached configuration
	 */
	public UseractivitiesDao(Configuration configuration) {
		super(UseractivitiesTable.USERACTIVITIES, Useractivities.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(Useractivities object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<Useractivities> fetchById(Integer... values) {
		return fetch(UseractivitiesTable.USERACTIVITIES.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public Useractivities fetchOneById(Integer value) {
		return fetchOne(UseractivitiesTable.USERACTIVITIES.ID, value);
	}

	/**
	 * Fetch records that have <code>activity_id IN (values)</code>
	 */
	public List<Useractivities> fetchByActivityId(Integer... values) {
		return fetch(UseractivitiesTable.USERACTIVITIES.ACTIVITY_ID, values);
	}

	/**
	 * Fetch records that have <code>user_id IN (values)</code>
	 */
	public List<Useractivities> fetchByUserId(Integer... values) {
		return fetch(UseractivitiesTable.USERACTIVITIES.USER_ID, values);
	}
}
