/**
 * This class is generated by jOOQ
 */
package org.jooq.ateamcomp354.projectmanagerapp.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.ateamcomp354.projectmanagerapp.tables.UsersTable;
import org.jooq.ateamcomp354.projectmanagerapp.tables.pojos.Users;
import org.jooq.ateamcomp354.projectmanagerapp.tables.records.UsersRecord;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersDao extends DAOImpl<UsersRecord, Users, Integer> {

	/**
	 * Create a new UsersDao without any configuration
	 */
	public UsersDao() {
		super(UsersTable.USERS, Users.class);
	}

	/**
	 * Create a new UsersDao with an attached configuration
	 */
	public UsersDao(Configuration configuration) {
		super(UsersTable.USERS, Users.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(Users object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<Users> fetchById(Integer... values) {
		return fetch(UsersTable.USERS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public Users fetchOneById(Integer value) {
		return fetchOne(UsersTable.USERS.ID, value);
	}

	/**
	 * Fetch records that have <code>first_name IN (values)</code>
	 */
	public List<Users> fetchByFirstName(String... values) {
		return fetch(UsersTable.USERS.FIRST_NAME, values);
	}

	/**
	 * Fetch records that have <code>last_name IN (values)</code>
	 */
	public List<Users> fetchByLastName(String... values) {
		return fetch(UsersTable.USERS.LAST_NAME, values);
	}

	/**
	 * Fetch records that have <code>username IN (values)</code>
	 */
	public List<Users> fetchByUsername(String... values) {
		return fetch(UsersTable.USERS.USERNAME, values);
	}

	/**
	 * Fetch records that have <code>password IN (values)</code>
	 */
	public List<Users> fetchByPassword(String... values) {
		return fetch(UsersTable.USERS.PASSWORD, values);
	}

	/**
	 * Fetch records that have <code>manager_role IN (values)</code>
	 */
	public List<Users> fetchByManagerRole(Boolean... values) {
		return fetch(UsersTable.USERS.MANAGER_ROLE, values);
	}
}
