/**
 * This class is generated by jOOQ
 */
package org.jooq.ateamcomp354.projectmanagerapp.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Activitylinks implements Serializable {

	private static final long serialVersionUID = -1784410872;

	private Integer id;
	private Integer fromActivityId;
	private Integer toActivityId;

	public Activitylinks() {}

	public Activitylinks(Activitylinks value) {
		this.id = value.id;
		this.fromActivityId = value.fromActivityId;
		this.toActivityId = value.toActivityId;
	}

	public Activitylinks(
		Integer id,
		Integer fromActivityId,
		Integer toActivityId
	) {
		this.id = id;
		this.fromActivityId = fromActivityId;
		this.toActivityId = toActivityId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getFromActivityId() {
		return this.fromActivityId;
	}

	public void setFromActivityId(Integer fromActivityId) {
		this.fromActivityId = fromActivityId;
	}

	public Integer getToActivityId() {
		return this.toActivityId;
	}

	public void setToActivityId(Integer toActivityId) {
		this.toActivityId = toActivityId;
	}
}
