/**
 * This class is generated by jOOQ
 */
package org.jooq.ateamcomp354.projectmanagerapp.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Activity implements Serializable {

	private static final long serialVersionUID = -256898937;

	private Integer id;
	private Integer projectId;
	private Integer earliestStart;
	private Integer earliestFinish;
	private String  label;
	private Integer latestStart;
	private Integer latestFinish;
	private Integer duration;
	private Integer maxDuration;

	public Activity() {}

	public Activity(Activity value) {
		this.id = value.id;
		this.projectId = value.projectId;
		this.earliestStart = value.earliestStart;
		this.earliestFinish = value.earliestFinish;
		this.label = value.label;
		this.latestStart = value.latestStart;
		this.latestFinish = value.latestFinish;
		this.duration = value.duration;
		this.maxDuration = value.maxDuration;
	}

	public Activity(
		Integer id,
		Integer projectId,
		Integer earliestStart,
		Integer earliestFinish,
		String  label,
		Integer latestStart,
		Integer latestFinish,
		Integer duration,
		Integer maxDuration
	) {
		this.id = id;
		this.projectId = projectId;
		this.earliestStart = earliestStart;
		this.earliestFinish = earliestFinish;
		this.label = label;
		this.latestStart = latestStart;
		this.latestFinish = latestFinish;
		this.duration = duration;
		this.maxDuration = maxDuration;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	public Integer getEarliestStart() {
		return this.earliestStart;
	}

	public void setEarliestStart(Integer earliestStart) {
		this.earliestStart = earliestStart;
	}

	public Integer getEarliestFinish() {
		return this.earliestFinish;
	}

	public void setEarliestFinish(Integer earliestFinish) {
		this.earliestFinish = earliestFinish;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public Integer getLatestStart() {
		return this.latestStart;
	}

	public void setLatestStart(Integer latestStart) {
		this.latestStart = latestStart;
	}

	public Integer getLatestFinish() {
		return this.latestFinish;
	}

	public void setLatestFinish(Integer latestFinish) {
		this.latestFinish = latestFinish;
	}

	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	public Integer getMaxDuration() {
		return this.maxDuration;
	}

	public void setMaxDuration(Integer maxDuration) {
		this.maxDuration = maxDuration;
	}
}
