/**
 * This class is generated by jOOQ
 */
package org.jooq.ateamcomp354.projectmanagerapp.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Memberlist implements Serializable {

	private static final long serialVersionUID = -1598386353;

	private Integer memberListId;
	private Integer userId;

	public Memberlist() {}

	public Memberlist(Memberlist value) {
		this.memberListId = value.memberListId;
		this.userId = value.userId;
	}

	public Memberlist(
		Integer memberListId,
		Integer userId
	) {
		this.memberListId = memberListId;
		this.userId = userId;
	}

	public Integer getMemberListId() {
		return this.memberListId;
	}

	public void setMemberListId(Integer memberListId) {
		this.memberListId = memberListId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}
}
