/**
 * This class is generated by jOOQ
 */
package org.jooq.ateamcomp354.projectmanagerapp.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Project implements Serializable {

	private static final long serialVersionUID = -1842446426;

	private Integer id;
	private String  projectName;
	private Integer projectManagerId;
	private String  description;

	public Project() {}

	public Project(Project value) {
		this.id = value.id;
		this.projectName = value.projectName;
		this.projectManagerId = value.projectManagerId;
		this.description = value.description;
	}

	public Project(
		Integer id,
		String  projectName,
		Integer projectManagerId,
		String  description
	) {
		this.id = id;
		this.projectName = projectName;
		this.projectManagerId = projectManagerId;
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public Integer getProjectManagerId() {
		return this.projectManagerId;
	}

	public void setProjectManagerId(Integer projectManagerId) {
		this.projectManagerId = projectManagerId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
}
