/**
 * This class is generated by jOOQ
 */
package org.jooq.ateamcomp354.projectmanagerapp.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SqliteSequence implements Serializable {

	private static final long serialVersionUID = -1177391122;

	private Object name;
	private Object seq;

	public SqliteSequence() {}

	public SqliteSequence(SqliteSequence value) {
		this.name = value.name;
		this.seq = value.seq;
	}

	public SqliteSequence(
		Object name,
		Object seq
	) {
		this.name = name;
		this.seq = seq;
	}

	public Object getName() {
		return this.name;
	}

	public void setName(Object name) {
		this.name = name;
	}

	public Object getSeq() {
		return this.seq;
	}

	public void setSeq(Object seq) {
		this.seq = seq;
	}
}
