/**
 * This class is generated by jOOQ
 */
package org.jooq.ateamcomp354.projectmanagerapp.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

	private static final long serialVersionUID = -611857019;

	private Integer id;
	private String  firstName;
	private String  lastName;
	private String  username;
	private String  password;
	private Integer managerRole;

	public Users() {}

	public Users(Users value) {
		this.id = value.id;
		this.firstName = value.firstName;
		this.lastName = value.lastName;
		this.username = value.username;
		this.password = value.password;
		this.managerRole = value.managerRole;
	}

	public Users(
		Integer id,
		String  firstName,
		String  lastName,
		String  username,
		String  password,
		Integer managerRole
	) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.username = username;
		this.password = password;
		this.managerRole = managerRole;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getManagerRole() {
		return this.managerRole;
	}

	public void setManagerRole(Integer managerRole) {
		this.managerRole = managerRole;
	}
}
