/**
 * This class is generated by jOOQ
 */
package org.jooq.ateamcomp354.projectmanagerapp.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Userprojects implements Serializable {

	private static final long serialVersionUID = -978579504;

	private Integer userId;
	private Integer projectId;

	public Userprojects() {}

	public Userprojects(Userprojects value) {
		this.userId = value.userId;
		this.projectId = value.projectId;
	}

	public Userprojects(
		Integer userId,
		Integer projectId
	) {
		this.userId = userId;
		this.projectId = projectId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}
}
