/**
 * This class is generated by jOOQ
 */
package org.jooq.ateamcomp354.projectmanagerapp;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.ateamcomp354.projectmanagerapp.tables.Activity;
import org.jooq.ateamcomp354.projectmanagerapp.tables.Activitylinks;
import org.jooq.ateamcomp354.projectmanagerapp.tables.Project;
import org.jooq.ateamcomp354.projectmanagerapp.tables.Useractivities;
import org.jooq.ateamcomp354.projectmanagerapp.tables.Users;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

	private static final long serialVersionUID = 678141362;

	/**
	 * The reference instance of <code></code>
	 */
	public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

	/**
	 * No further instances allowed
	 */
	private DefaultSchema() {
		super("");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Activity.ACTIVITY,
			Activitylinks.ACTIVITYLINKS,
			Project.PROJECT,
			Useractivities.USERACTIVITIES,
			Users.USERS);
	}
}
