/**
 * This class is generated by jOOQ
 */
package org.jooq.ateamcomp354.projectmanagerapp;


import javax.annotation.Generated;

import org.jooq.ateamcomp354.projectmanagerapp.tables.ActivityTable;
import org.jooq.ateamcomp354.projectmanagerapp.tables.ActivitylinksTable;
import org.jooq.ateamcomp354.projectmanagerapp.tables.ProjectTable;
import org.jooq.ateamcomp354.projectmanagerapp.tables.ProjectmembersTable;
import org.jooq.ateamcomp354.projectmanagerapp.tables.UseractivitiesTable;
import org.jooq.ateamcomp354.projectmanagerapp.tables.UsersTable;


/**
 * Convenience access to all tables in 
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table activity
	 */
	public static final ActivityTable ACTIVITY = org.jooq.ateamcomp354.projectmanagerapp.tables.ActivityTable.ACTIVITY;

	/**
	 * The table activityLinks
	 */
	public static final ActivitylinksTable ACTIVITYLINKS = org.jooq.ateamcomp354.projectmanagerapp.tables.ActivitylinksTable.ACTIVITYLINKS;

	/**
	 * The table project
	 */
	public static final ProjectTable PROJECT = org.jooq.ateamcomp354.projectmanagerapp.tables.ProjectTable.PROJECT;

	/**
	 * The table projectMembers
	 */
	public static final ProjectmembersTable PROJECTMEMBERS = org.jooq.ateamcomp354.projectmanagerapp.tables.ProjectmembersTable.PROJECTMEMBERS;

	/**
	 * The table userActivities
	 */
	public static final UseractivitiesTable USERACTIVITIES = org.jooq.ateamcomp354.projectmanagerapp.tables.UseractivitiesTable.USERACTIVITIES;

	/**
	 * The table users
	 */
	public static final UsersTable USERS = org.jooq.ateamcomp354.projectmanagerapp.tables.UsersTable.USERS;
}
