/**
 * This class is generated by jOOQ
 */
package org.jooq.ateamcomp354.projectmanagerapp;


import javax.annotation.Generated;

import org.jooq.ateamcomp354.projectmanagerapp.tables.SqliteSequence;
import org.jooq.ateamcomp354.projectmanagerapp.tables.Users;


/**
 * Convenience access to all tables in 
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table sqlite_sequence
	 */
	public static final SqliteSequence SQLITE_SEQUENCE = org.jooq.ateamcomp354.projectmanagerapp.tables.SqliteSequence.SQLITE_SEQUENCE;

	/**
	 * The table users
	 */
	public static final Users USERS = org.jooq.ateamcomp354.projectmanagerapp.tables.Users.USERS;
}
